replicaCount: 2

image:
  repository: your-docker-registry/your-app
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: APP_ENV
    value: production
  - name: LOG_LEVEL
    value: INFO

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80

livenessProbe:
  path: /health
  port: 8080
