apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-chart.fullname" . }}
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "common-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
