name: Reusable Java Build

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build --info

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app_name }}-jar
          path: build/libs/*.jar
