name: Reusable Artifact Publish

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.path }}
